### ISSUE TITLE
Firefox crashed when I ran `node bin/dc.js run -b firefox`.

### ISSUE THREAD

**Issue by yat1ma30** [Mah-D/DwarfCucumber#2]
`node bin/dc.js run -b firefox` didn't work.
## Env
- Firefox v38
- OS: Mac OS X 10.10.4 x86_64
- Webdriver v2.43.1, with Core v2.43.1. Built from revision 5163bce
## Solved

So, I downgraded my Firefox back to v32.0b9 and it was solved.
You can download the version of Firefox from [here](https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/).

It was some sort of driver problem :D

**Comment by Mah-D** [comment]
Great.
Thanks for clarification.
